show
Configured parameters:
	port1 	IPv4 IP: 10.101.11.110/24 	MAC: 00:90:0B:D9:9D:67
		MTU: 1500
		speed: 1000Mb/s
		duplex: full
	port2 	IPv4 IP: 192.168.1.99/24 	MAC: 00:90:0B:D9:9D:68
		MTU: 1500
		disconnected
	port3 	IPv4 IP: 10.8.8.2/28 	MAC: 00:90:0B:D9:9D:69
		MTU: 1500
		speed: 1000Mb/s
		duplex: full
	port4 	IPv4 IP: 192.168.3.99/24 	MAC: 00:90:0B:D9:9D:6A
		MTU: 1500
		disconnected
	IPv4 Default Gateway: 10.101.11.1
	Administration interface(s): port1
	API interface(s):
FortiSandBox> 